### ISSUE TITLE
[UI] - Design the profile page

### ISSUE THREAD

**Issue by earmuff-jam** [earmuff-jam/climate-app#17] opened 2024-03-01 01:24 UTC
## Acceptance Criteria

1. Design the profile page. The profile page should at least be able to create, update, read, delete tags and categories. Design for tags and capabilities color scheme is being worked on in issue #16  . 
2. Design the ability to edit profile username and couple of other fields that are still being worked out.
3. Archived categories will be displayed as minimalistic as possible. Since archived categories are disbanded we want to refrain from displaying more information.

**Comment by earmuff-jam** [comment] 2024-03-01 01:24
We would like to view a couple of design first and then only choose the best looking design. maybe storybook would be ready by then ?

**Comment by mohit2530** [comment] 2024-03-01 14:48
Duplicate of #16

**Closed by mohit2530** 2024-03-01 14:48 UTC
Labels: duplicate
